<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\01.Core\SYST.Core.Abstractions\SYST.Core.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Manifests\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
